interface ColorsType {
    name: string;
    class: string;
    shades: Array<{ color: string; shade: number; selected: boolean }>;
}

// create type for colors
type possibleColors = "" | "primary" | "gray" | "red" | "orange" | "amber" | "yellow" | "lime" | "green" | "emerald" | "teal" | "cyan" | "lightBlue" | "blue" | "indigo" | "violet" | "purple" | "fuchsia" | "pink" | "rose" | "warmGray" | "trueGray" | "coolGray" | "blueGray";



let colorList = [
    {
        name: 'gray',
        class: '#a5a5a5',
        shades: [
            { color: '#f3f4f6', shade: 100, selected: false },
            { color: '#e5e7eb', shade: 200, selected: false },
            { color: '#d1d5db', shade: 300, selected: false },
            { color: '#9ca3af', shade: 400, selected: false },
            { color: '#6b7280', shade: 500, selected: false },
            { color: '#3d3d3d', shade: 600, selected: false },
            { color: '#1f1f1f', shade: 700, selected: false },
            { color: '#101010', shade: 800, selected: false },
            { color: '#000000', shade: 900, selected: false },
        ],
    },
    {
        name: 'red',
        class: '#ef4444',
        shades: [
            { color: '#fee2e2', shade: 100, selected: false },
            { color: '#fecaca', shade: 200, selected: false },
            { color: '#fca5a5', shade: 300, selected: false },
            { color: '#f87171', shade: 400, selected: false },
            { color: '#ef4444', shade: 500, selected: false },
            { color: '#dc2626', shade: 600, selected: false },
            { color: '#b91c1c', shade: 700, selected: false },
            { color: '#991b1b', shade: 800, selected: false },
            { color: '#7f1d1d', shade: 900, selected: false },
        ],
    },
    {
        name: 'orange',
        class: '#fb923c',
        shades: [
            { color: '#ffedd5', shade: 100, selected: false },
            { color: '#fed7aa', shade: 200, selected: false },
            { color: '#fdba74', shade: 300, selected: false },
            { color: '#fb923c', shade: 400, selected: false },
            { color: '#f97316', shade: 500, selected: false },
            { color: '#ea580c', shade: 600, selected: false },
            { color: '#c2410c', shade: 700, selected: false },
            { color: '#9a3412', shade: 800, selected: false },
            { color: '#7c2d12', shade: 900, selected: false },
        ],
    },
    {
        name: 'amber',
        class: '#fbbf24',
        shades: [
            { color: '#fef3c7', shade: 100, selected: false },
            { color: '#fde68a', shade: 200, selected: false },
            { color: '#fcd34d', shade: 300, selected: false },
            { color: '#fbbf24', shade: 400, selected: false },
            { color: '#f59e0b', shade: 500, selected: false },
            { color: '#d97706', shade: 600, selected: false },
            { color: '#b45309', shade: 700, selected: false },
            { color: '#92400e', shade: 800, selected: false },
            { color: '#78350f', shade: 900, selected: false },
        ],
    },
    {
        name: 'yellow',
        class: '#facc15',
        shades: [
            { color: '#fef9c3', shade: 100, selected: false },
            { color: '#fef08a', shade: 200, selected: false },
            { color: '#fde047', shade: 300, selected: false },
            { color: '#facc15', shade: 400, selected: false },
            { color: '#eab308', shade: 500, selected: false },
            { color: '#ca8a04', shade: 600, selected: false },
            { color: '#a16207', shade: 700, selected: false },
            { color: '#854d0e', shade: 800, selected: false },
            { color: '#713f12', shade: 900, selected: false },
        ],
    },
    {
        name: 'lime',
        class: '#a3e635',
        shades: [
            { color: '#ecfccb', shade: 100, selected: false },
            { color: '#d9f99d', shade: 200, selected: false },
            { color: '#bef264', shade: 300, selected: false },
            { color: '#a3e635', shade: 400, selected: false },
            { color: '#84cc16', shade: 500, selected: false },
            { color: '#65a30d', shade: 600, selected: false },
            { color: '#4d7c0f', shade: 700, selected: false },
            { color: '#3f6212', shade: 800, selected: false },
            { color: '#365314', shade: 900, selected: false },
        ],
    },
    {
        name: 'green',
        class: '#4ade80',
        shades: [
            { color: '#dcfce7', shade: 100, selected: false },
            { color: '#bbf7d0', shade: 200, selected: false },
            { color: '#86efac', shade: 300, selected: false },
            { color: '#4ade80', shade: 400, selected: false },
            { color: '#22c55e', shade: 500, selected: false },
            { color: '#16a34a', shade: 600, selected: false },
            { color: '#15803d', shade: 700, selected: false },
            { color: '#166534', shade: 800, selected: false },
            { color: '#14532d', shade: 900, selected: false },
        ],
    },
    {
        name: 'emerald',
        class: '#34d399',
        shades: [
            { color: '#d1fae5', shade: 100, selected: false },
            { color: '#a7f3d0', shade: 200, selected: false },
            { color: '#6ee7b7', shade: 300, selected: false },
            { color: '#34d399', shade: 400, selected: false },
            { color: '#10b981', shade: 500, selected: false },
            { color: '#059669', shade: 600, selected: false },
            { color: '#047857', shade: 700, selected: false },
            { color: '#065f46', shade: 800, selected: false },
            { color: '#064e3b', shade: 900, selected: false },
        ],
    },
    {
        name: 'teal',
        class: '#2dd4bf',
        shades: [
            { color: '#ccfbf1', shade: 100, selected: false },
            { color: '#99f6e4', shade: 200, selected: false },
            { color: '#5eead4', shade: 300, selected: false },
            { color: '#2dd4bf', shade: 400, selected: false },
            { color: '#14b8a6', shade: 500, selected: false },
            { color: '#0d9488', shade: 600, selected: false },
            { color: '#0f766e', shade: 700, selected: false },
            { color: '#115e59', shade: 800, selected: false },
            { color: '#134e4a', shade: 900, selected: false },
        ],
    },
    {
        name: 'cyan',
        class: '#22d3ee',
        shades: [
            { color: '#cffafe', shade: 100, selected: false },
            { color: '#a5f3fc', shade: 200, selected: false },
            { color: '#67e8f9', shade: 300, selected: false },
            { color: '#22d3ee', shade: 400, selected: false },
            { color: '#06b6d4', shade: 500, selected: false },
            { color: '#0891b2', shade: 600, selected: false },
            { color: '#0e7490', shade: 700, selected: false },
            { color: '#155e75', shade: 800, selected: false },
            { color: '#164e63', shade: 900, selected: false },
        ],
    },
    {
        name: 'sky',
        class: '#38bdf8',
        shades: [
            { color: '#e0f2fe', shade: 100, selected: false },
            { color: '#bae6fd', shade: 200, selected: false },
            { color: '#7dd3fc', shade: 300, selected: false },
            { color: '#38bdf8', shade: 400, selected: false },
            { color: '#0ea5e9', shade: 500, selected: false },
            { color: '#0284c7', shade: 600, selected: false },
            { color: '#0369a1', shade: 700, selected: false },
            { color: '#075985', shade: 800, selected: false },
            { color: '#0c4a6e', shade: 900, selected: false },
        ],
    },
    {
        name: 'blue',
        class: '#60a5fa',
        shades: [
            { color: '#dbeafe', shade: 100, selected: false },
            { color: '#bfdbfe', shade: 200, selected: false },
            { color: '#93c5fd', shade: 300, selected: false },
            { color: '#60a5fa', shade: 400, selected: false },
            { color: '#3b82f6', shade: 500, selected: false },
            { color: '#2563eb', shade: 600, selected: false },
            { color: '#1d4ed8', shade: 700, selected: false },
            { color: '#1e40af', shade: 800, selected: false },
            { color: '#1e3a8a', shade: 900, selected: false },
        ],
    },
    {
        name: 'indigo',
        class: '#818cf8',
        shades: [
            { color: '#e0e7ff', shade: 100, selected: false },
            { color: '#c7d2fe', shade: 200, selected: false },
            { color: '#a5b4fc', shade: 300, selected: false },
            { color: '#818cf8', shade: 400, selected: false },
            { color: '#6366f1', shade: 500, selected: false },
            { color: '#4f46e5', shade: 600, selected: false },
            { color: '#4338ca', shade: 700, selected: false },
            { color: '#3730a3', shade: 800, selected: false },
            { color: '#312e81', shade: 900, selected: false },
        ],
    },
    {
        name: 'violet',
        class: '#a78bfa',
        shades: [
            { color: '#ede9fe', shade: 100, selected: false },
            { color: '#ddd6fe', shade: 200, selected: false },
            { color: '#c4b5fd', shade: 300, selected: false },
            { color: '#a78bfa', shade: 400, selected: false },
            { color: '#8b5cf6', shade: 500, selected: false },
            { color: '#7c3aed', shade: 600, selected: false },
            { color: '#6d28d9', shade: 700, selected: false },
            { color: '#5b21b6', shade: 800, selected: false },
            { color: '#4c1d95', shade: 900, selected: false },
        ],
    },
    {
        name: 'purple',
        class: '#c084fc',
        shades: [
            { color: '#f3e8ff', shade: 100, selected: false },
            { color: '#e9d5ff', shade: 200, selected: false },
            { color: '#d8b4fe', shade: 300, selected: false },
            { color: '#c084fc', shade: 400, selected: false },
            { color: '#a855f7', shade: 500, selected: false },
            { color: '#9333ea', shade: 600, selected: false },
            { color: '#7e22ce', shade: 700, selected: false },
            { color: '#6b21a8', shade: 800, selected: false },
            { color: '#581c87', shade: 900, selected: false },
        ],
    },
    {
        name: 'fuchsia',
        class: '#e879f9',
        shades: [
            { color: '#fae8ff', shade: 100, selected: false },
            { color: '#f5d0fe', shade: 200, selected: false },
            { color: '#f0abfc', shade: 300, selected: false },
            { color: '#e879f9', shade: 400, selected: false },
            { color: '#d946ef', shade: 500, selected: false },
            { color: '#c026d3', shade: 600, selected: false },
            { color: '#a21caf', shade: 700, selected: false },
            { color: '#86198f', shade: 800, selected: false },
            { color: '#701a75', shade: 900, selected: false },
        ],
    },
    {
        name: 'pink',
        class: '#f472b6',
        shades: [
            { color: '#fce7f3', shade: 100, selected: false },
            { color: '#fbcfe8', shade: 200, selected: false },
            { color: '#f9a8d4', shade: 300, selected: false },
            { color: '#f472b6', shade: 400, selected: false },
            { color: '#ec4899', shade: 500, selected: false },
            { color: '#db2777', shade: 600, selected: false },
            { color: '#be185d', shade: 700, selected: false },
            { color: '#9d174d', shade: 800, selected: false },
            { color: '#831843', shade: 900, selected: false },
        ],
    },
    {
        name: 'rose',
        class: '#fb7185',
        shades: [
            { color: '#ffe4e6', shade: 100, selected: false },
            { color: '#fecdd3', shade: 200, selected: false },
            { color: '#fda4af', shade: 300, selected: false },
            { color: '#fb7185', shade: 400, selected: false },
            { color: '#f43f5e', shade: 500, selected: false },
            { color: '#e11d48', shade: 600, selected: false },
            { color: '#be123c', shade: 700, selected: false },
            { color: '#9f1239', shade: 800, selected: false },
            { color: '#881337', shade: 900, selected: false },
        ],
    },
];

export { colorList, ColorsType, possibleColors };
